//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Data_TermProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemInfo
    {
        public int itemid { get; set; }
        public string ItemName { get; set; }
        public string ItemMake { get; set; }
        public int Itemyear { get; set; }
        public string ItemType { get; set; }
        public string item_img { get; set; }
    }
}
