//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Data_TermProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        public int Reserveid { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Email { get; set; }
        public string Carmake { get; set; }
        public string Carmodel { get; set; }
        public int CarYear { get; set; }
    }
}
