//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Data_TermProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinRecord
    {
        public int id { get; set; }
        public string Username { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Auctionname { get; set; }
    }
}
